apiVersion: v1
kind: Secret
metadata:
  name: devhub-secrets
  namespace: devhub
type: Opaque
stringData:
  GERRIT_USER: ""
  GERRIT_HTTP_PASSWORD: ""
  JENKINS_URL: ""
  JENKINS_USER: ""
  JENKINS_API_TOKEN: ""
  JIRA_URL: ""
  JIRA_TOKEN: ""
  CONFLUENCE_URL: ""
  CONFLUENCE_TOKEN: ""
